#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_FILE="${ROOT_DIR}/data/robotaxi-operations.yaml"
OUTPUT_FILE="${ROOT_DIR}/supabase/seeds/robotaxi-operations.sql"

if [[ ! -f "${DATA_FILE}" ]]; then
  echo "Missing data file: ${DATA_FILE}" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to generate the seed file." >&2
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT_FILE}")"

python3 - "${DATA_FILE}" "${OUTPUT_FILE}" <<'PY'
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ModuleNotFoundError as exc:
    sys.stderr.write(
        "PyYAML is required to generate the robotaxi operations seed.\n"
        "Install it with `pip install pyyaml` and re-run the script.\n"
    )
    raise SystemExit(1) from exc

input_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])

if not input_path.exists():
    raise SystemExit(f"Input file not found: {input_path}")

raw_data = input_path.read_text(encoding="utf-8")
data: Any = yaml.safe_load(raw_data)

if not isinstance(data, list):
    raise SystemExit("Expected a top-level YAML sequence of robotaxi-operations records.")

timestamp = datetime.now(tz=timezone.utc).isoformat()

city_rows: set[tuple[str, str]] = set()

def normalize_slug(value: Any, kind: str, context: str) -> str:
    if not isinstance(value, (str, int, float)):
        raise SystemExit(
            f"Expected {kind} slug to be a scalar string for {context}, got {type(value)!r}"
        )
    slug = str(value).strip()
    if not slug:
        raise SystemExit(f"Encountered empty {kind} slug for {context}.")
    return slug

for idx, entry in enumerate(data):
    if not isinstance(entry, dict):
        raise SystemExit(f"Entry at index {idx} is not a mapping.")

    robotaxi_slug = entry.get("robotaxi-slug")
    if robotaxi_slug is None:
        raise SystemExit(f"Missing robotaxi-slug for entry at index {idx}.")

    robotaxi_slug = normalize_slug(robotaxi_slug, "robotaxi", f"entry at index {idx}")
    context = f"robotaxi '{robotaxi_slug}'"

    cities = entry.get("cities", [])
    if cities is None:
        cities = []
    if not isinstance(cities, list):
        raise SystemExit(f"Expected 'cities' list for {context}.")

    seen: set[str] = set()
    for city in cities:
        city_slug = normalize_slug(city, "city", context)
        if city_slug in seen:
            continue
        seen.add(city_slug)
        city_rows.add((robotaxi_slug, city_slug))

if not city_rows:
    raise SystemExit("No city operations data found in the YAML source.")

def sql_escape(value: str) -> str:
    return value.replace("'", "''")

sorted_rows = sorted(city_rows)

with output_path.open("w", encoding="utf-8") as fh:
    fh.write("-- Seed: robotaxi-operations\n")
    fh.write("-- File generated by scripts/generate_robotaxi_operations_seed.sh\n")
    fh.write(f"-- Source: {input_path}\n")
    fh.write(f"-- Generated at: {timestamp}\n\n")
    fh.write("BEGIN;\n")
    fh.write("TRUNCATE TABLE public.robotaxi_city_operations RESTART IDENTITY CASCADE;\n\n")
    fh.write("INSERT INTO public.robotaxi_city_operations (robotaxi_slug, city_slug)\nVALUES\n")

    for idx, (robotaxi_slug, city_slug) in enumerate(sorted_rows):
        prefix = "  " if idx == 0 else ", "
        fh.write(f"{prefix}('{sql_escape(robotaxi_slug)}', '{sql_escape(city_slug)}')\n")

    fh.write("ON CONFLICT (robotaxi_slug, city_slug) DO NOTHING;\n\n")
    fh.write("COMMIT;\n")

print(f"Wrote {len(sorted_rows)} city operations to {output_path}")
PY

echo "Seed written to ${OUTPUT_FILE}"
