#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_FILE="${ROOT_DIR}/data/robotaxis.yaml"
OUTPUT_FILE="${ROOT_DIR}/supabase/seeds/robotaxis.sql"

if [[ ! -f "${DATA_FILE}" ]]; then
  echo "Missing data file: ${DATA_FILE}" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to generate the seed file." >&2
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT_FILE}")"

python3 - "${DATA_FILE}" "${OUTPUT_FILE}" <<'PY'
import sys
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ModuleNotFoundError as exc:
    sys.stderr.write(
        "PyYAML is required to generate the robotaxis seed.\n"
        "Install it with `pip install pyyaml` and re-run the script.\n"
    )
    raise SystemExit(1) from exc

input_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])

if not input_path.exists():
    raise SystemExit(f"Input file not found: {input_path}")

raw_data = input_path.read_text(encoding="utf-8")
data: Any = yaml.safe_load(raw_data)

if not isinstance(data, list):
    raise SystemExit("Expected a top-level YAML sequence of robotaxi records.")

required_fields = ("slug", "name", "city", "country", "latitude", "longitude")
columns = [
    "slug",
    "name",
    "website",
    "city_slug",
    "country_slug",
    "latitude",
    "longitude",
    "address",
]


def sanitize_string(value: str) -> str:
    return value.replace("'", "''")


def format_decimal(value: Any, column: str) -> str:
    try:
        decimal_value = Decimal(str(value))
    except InvalidOperation as exc:
        raise SystemExit(f"Invalid {column} value '{value}'") from exc
    return format(decimal_value, ".6f")


def format_value(value: Any, column: str) -> str:
    if value is None:
        return "NULL"

    if column in {"latitude", "longitude"}:
        return format_decimal(value, column)

    if isinstance(value, str):
        trimmed = value.strip()
        if trimmed == "":
            return "NULL"
        return f"'{sanitize_string(trimmed)}'"

    return str(value)


records: dict[str, dict[str, Any]] = {}

for idx, item in enumerate(data):
    if not isinstance(item, dict):
        continue

    missing = [
        field
        for field in required_fields
        if str(item.get(field) or "").strip() == ""
    ]
    if missing:
        raise SystemExit(
            f"Missing required field(s) {missing} for record at index {idx}."
        )

    slug = str(item["slug"]).strip()
    if slug in records:
        raise SystemExit(f"Duplicate robotaxi slug detected: {slug}")

    record = {
        "slug": slug,
        "name": str(item["name"]).strip(),
        "website": item.get("website"),
        "city_slug": str(item["city"]).strip(),
        "country_slug": str(item["country"]).strip(),
        "latitude": item.get("latitude"),
        "longitude": item.get("longitude"),
        "address": item.get("address"),
    }

    records[slug] = record

if not records:
    raise SystemExit("No valid robotaxi records were found in the YAML source.")

timestamp = datetime.now(tz=timezone.utc).isoformat()
sorted_records = [records[key] for key in sorted(records.keys())]

with output_path.open("w", encoding="utf-8") as fh:
    fh.write("-- Seed: robotaxis\n")
    fh.write("-- File generated by scripts/generate_robotaxis_migration.sh\n")
    fh.write(f"-- Source: {input_path}\n")
    fh.write(f"-- Generated at: {timestamp}\n\n")

    fh.write("BEGIN;\n")
    fh.write("TRUNCATE TABLE public.robotaxis RESTART IDENTITY CASCADE;\n\n")

    fh.write(
        "INSERT INTO public.robotaxis (slug, name, website, city_slug, country_slug, latitude, longitude, address)\n"
        "VALUES\n"
    )

    for idx, record in enumerate(sorted_records):
        formatted_values = ", ".join(
            format_value(record.get(column), column) for column in columns
        )
        prefix = "  " if idx == 0 else ", "
        fh.write(f"{prefix}({formatted_values})\n")

    fh.write(
        "ON CONFLICT (slug) DO UPDATE SET\n"
        "  name = EXCLUDED.name,\n"
        "  website = EXCLUDED.website,\n"
        "  city_slug = EXCLUDED.city_slug,\n"
        "  country_slug = EXCLUDED.country_slug,\n"
        "  latitude = EXCLUDED.latitude,\n"
        "  longitude = EXCLUDED.longitude,\n"
        "  address = EXCLUDED.address,\n"
        "  updated_at = now();\n\n"
    )

    fh.write("COMMIT;\n")

print(f"Wrote {len(sorted_records)} robotaxi records to {output_path}")
PY

echo "Seed written to ${OUTPUT_FILE}"


