#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_FILE="${ROOT_DIR}/data/universities.yaml"
OUTPUT_FILE="${ROOT_DIR}/supabase/seeds/universities.sql"

if [[ ! -f "${DATA_FILE}" ]]; then
  echo "Missing data file: ${DATA_FILE}" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to generate the seed file." >&2
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT_FILE}")"

python3 - "${DATA_FILE}" "${OUTPUT_FILE}" <<'PY'
import sys
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path

try:
    import yaml  # type: ignore
except ModuleNotFoundError as exc:
    sys.stderr.write(
        "PyYAML is required to generate the universities seed.\n"
        "Install it with `pip install pyyaml` and re-run the script.\n"
    )
    raise SystemExit(1) from exc

input_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])

if not input_path.exists():
    raise SystemExit(f"Input file not found: {input_path}")

raw_data = input_path.read_text(encoding="utf-8")
data = yaml.safe_load(raw_data)

if not isinstance(data, list):
    raise SystemExit("Expected a top-level YAML sequence of university objects.")

columns = [
    "slug",
    "name",
    "website",
    "country_iso",
    "latitude",
    "longitude",
    "city_name",
    "city_slug",
]


def sanitize_string(value: str) -> str:
    return value.replace("'", "''")


def format_decimal(value, column: str) -> str:
    try:
        decimal_value = Decimal(str(value))
    except InvalidOperation as exc:
        raise SystemExit(f"Invalid {column} value '{value}'") from exc
    return format(decimal_value, ".6f")


def format_value(value, column: str) -> str:
    if value is None:
        return "NULL"

    if column in {"latitude", "longitude"}:
        return format_decimal(value, column)

    if isinstance(value, str):
        trimmed = value.strip()
        if trimmed == "":
            return "NULL"
        return f"'{sanitize_string(trimmed)}'"

    return str(value)


def normalize_country_iso(raw) -> str | None:
    if raw is None:
        return None
    iso = str(raw).strip().upper()
    if iso == "":
        return None
    if len(iso) != 2 or not iso.isalpha():
        raise SystemExit(f"Invalid country ISO code '{raw}'")
    return iso


records: dict[str, dict] = {}
skipped_city_slug_mismatches = 0

cities_source_path = input_path.parent / "cities.yaml"
valid_city_slugs: set[str] = set()

if cities_source_path.exists():
    raw_cities = cities_source_path.read_text(encoding="utf-8")
    city_data = yaml.safe_load(raw_cities)
    if isinstance(city_data, list):
        for entry in city_data:
            if isinstance(entry, dict):
                slug = str(entry.get("slug") or "").strip()
                if slug:
                    valid_city_slugs.add(slug)
    else:
        sys.stderr.write(
            f"Warning: Expected list in {cities_source_path}, "
            "city slug validation disabled.\n"
        )
else:
    sys.stderr.write(
        f"Warning: {cities_source_path} missing, city slug validation disabled.\n"
    )

for idx, item in enumerate(data):
    if not isinstance(item, dict):
        continue

    slug = str(item.get("slug") or "").strip()
    name = str(item.get("name") or "").strip()
    city_slug = str(item.get("city") or "").strip()

    missing_fields = [
        field
        for field, value in (
            ("slug", slug),
            ("name", name),
            ("city", city_slug),
        )
        if value == ""
    ]

    if missing_fields:
        raise SystemExit(
            f"Missing required field(s) {missing_fields} for record at index {idx}."
        )

    if slug in records:
        raise SystemExit(f"Duplicate university slug detected: {slug}")

    lowercase_city_slug = city_slug.lower()
    if lowercase_city_slug.startswith("unknown"):
        skipped_city_slug_mismatches += 1
        continue

    if valid_city_slugs and city_slug not in valid_city_slugs:
        skipped_city_slug_mismatches += 1
        continue

    record = {
        "slug": slug,
        "name": name,
        "website": item.get("website"),
        "country_iso": normalize_country_iso(item.get("country_iso")),
        "latitude": item.get("latitude"),
        "longitude": item.get("longitude"),
        "city_name": item.get("city_name"),
        "city_slug": city_slug,
    }

    records[slug] = record

if not records:
    raise SystemExit("No valid university records were found in the YAML source.")

timestamp = datetime.now(tz=timezone.utc).isoformat()
sorted_records = [records[key] for key in sorted(records.keys())]

with output_path.open("w", encoding="utf-8") as fh:
    fh.write("-- File generated by scripts/generate_universities_seed.sh\n")
    fh.write(f"-- Source: {input_path}\n")
    fh.write(f"-- Generated at: {timestamp}\n\n")
    fh.write("BEGIN;\n")
    fh.write("TRUNCATE TABLE public.universities RESTART IDENTITY CASCADE;\n\n")
    fh.write(
        "INSERT INTO public.universities (slug, name, website, country_iso, latitude, longitude, city_name, city_slug)\n"
    )
    fh.write("VALUES\n")

    for idx, record in enumerate(sorted_records):
        formatted_values = ", ".join(
            format_value(record.get(column), column) for column in columns
        )
        prefix = "  " if idx == 0 else ", "
        fh.write(f"{prefix}({formatted_values})\n")

    fh.write(
        "ON CONFLICT (slug) DO UPDATE SET\n"
        "  name = EXCLUDED.name,\n"
        "  website = EXCLUDED.website,\n"
        "  country_iso = EXCLUDED.country_iso,\n"
        "  latitude = EXCLUDED.latitude,\n"
        "  longitude = EXCLUDED.longitude,\n"
        "  city_name = EXCLUDED.city_name,\n"
        "  city_slug = EXCLUDED.city_slug,\n"
        "  updated_at = now();\n\n"
    )
    fh.write("COMMIT;\n")

print(f"Wrote {len(sorted_records)} universities to {output_path}")
if skipped_city_slug_mismatches:
    print(
        f"Skipped {skipped_city_slug_mismatches} universities due to missing city slugs",
        file=sys.stderr,
    )
PY

echo "Seed written to ${OUTPUT_FILE}"

