#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_FILE="${ROOT_DIR}/data/operations.yaml"
OUTPUT_FILE="${ROOT_DIR}/supabase/seeds/operations.sql"

if [[ ! -f "${DATA_FILE}" ]]; then
  echo "Missing data file: ${DATA_FILE}" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to generate the seed file." >&2
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT_FILE}")"

python3 - "${DATA_FILE}" "${OUTPUT_FILE}" <<'PY'
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ModuleNotFoundError as exc:
    sys.stderr.write(
        "PyYAML is required to generate the operations seed.\n"
        "Install it with `pip install pyyaml` and re-run the script.\n"
    )
    raise SystemExit(1) from exc

input_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])

if not input_path.exists():
    raise SystemExit(f"Input file not found: {input_path}")

raw_data = input_path.read_text(encoding="utf-8")
data: Any = yaml.safe_load(raw_data)

if not isinstance(data, list):
    raise SystemExit("Expected a top-level YAML sequence of operations records.")

timestamp = datetime.now(tz=timezone.utc).isoformat()

country_rows: set[tuple[str, str]] = set()
city_rows: set[tuple[str, str]] = set()

def normalize_slug(value: Any, kind: str, context: str) -> str:
    if not isinstance(value, (str, int, float)):
        raise SystemExit(
            f"Expected {kind} slug to be a scalar string for {context}, got {type(value)!r}"
        )
    slug = str(value).strip()
    if not slug:
        raise SystemExit(f"Encountered empty {kind} slug for {context}.")
    return slug

for idx, entry in enumerate(data):
    if not isinstance(entry, dict):
        raise SystemExit(f"Entry at index {idx} is not a mapping.")

    ridehailing_slug = entry.get("ridehailing-slug")
    if ridehailing_slug is None:
        raise SystemExit(f"Missing ridehailing-slug for entry at index {idx}.")

    ridehailing_slug = normalize_slug(
        ridehailing_slug, "ridehailing", f"entry at index {idx}"
    )

    context = f"ridehailing '{ridehailing_slug}'"

    countries = entry.get("countries", [])
    if countries is None:
        countries = []
    if not isinstance(countries, list):
        raise SystemExit(f"Expected 'countries' list for {context}.")

    seen_country_slugs: set[str] = set()
    for country in countries:
        country_slug = normalize_slug(country, "country", context)
        if country_slug in seen_country_slugs:
            continue
        seen_country_slugs.add(country_slug)
        country_rows.add((ridehailing_slug, country_slug))

    cities = entry.get("cities", [])
    if cities is None:
        cities = []
    if not isinstance(cities, list):
        raise SystemExit(f"Expected 'cities' list for {context}.")

    seen_city_slugs: set[str] = set()
    for city in cities:
        city_slug = normalize_slug(city, "city", context)
        if city_slug in seen_city_slugs:
            continue
        seen_city_slugs.add(city_slug)
        city_rows.add((ridehailing_slug, city_slug))

if not country_rows and not city_rows:
    raise SystemExit("No operations data found in the YAML source.")

def sql_escape(value: str) -> str:
    return value.replace("'", "''")

def write_insert(
    fh,
    rows: list[tuple[str, str]],
    table: str,
    column: str,
) -> None:
    if not rows:
        fh.write(f"-- No rows for {table}\n\n")
        return

    fh.write(
        f"INSERT INTO {table} (ridehailing_slug, {column})\n"
        "VALUES\n"
    )

    for idx, (ridehailing_slug, location_slug) in enumerate(rows):
        prefix = "  " if idx == 0 else ", "
        fh.write(
            f"{prefix}('{sql_escape(ridehailing_slug)}', '{sql_escape(location_slug)}')\n"
        )

    conflict_target = f"(ridehailing_slug, {column})"
    fh.write(
        f"ON CONFLICT {conflict_target} DO NOTHING;\n\n"
    )

sorted_country_rows = sorted(country_rows)
sorted_city_rows = sorted(city_rows)

with output_path.open("w", encoding="utf-8") as fh:
    fh.write("-- Seed: operations\n")
    fh.write("-- File generated by scripts/generate_operations_seed.sh\n")
    fh.write(f"-- Source: {input_path}\n")
    fh.write(f"-- Generated at: {timestamp}\n\n")
    fh.write("BEGIN;\n")
    fh.write("TRUNCATE TABLE public.ridehailing_country_operations RESTART IDENTITY CASCADE;\n")
    fh.write("TRUNCATE TABLE public.ridehailing_city_operations RESTART IDENTITY CASCADE;\n\n")

    write_insert(
        fh,
        sorted_country_rows,
        "public.ridehailing_country_operations",
        "country_slug",
    )
    write_insert(
        fh,
        sorted_city_rows,
        "public.ridehailing_city_operations",
        "city_slug",
    )

    fh.write("COMMIT;\n")

print(
    f"Wrote {len(sorted_country_rows)} country operations and {len(sorted_city_rows)} city operations to {output_path}"
)
PY

echo "Seed written to ${OUTPUT_FILE}"


